services:
  - type: web
    name: events-manager
    runtime: docker
    plan: free
    dockerfilePath: Dockerfile
    healthCheckPath: /
    envVars:
      - key: APP_ENV
        value: prod
      - key: APP_DEBUG
        value: "0"
      - key: APP_SECRET
        generateValue: true
      - key: DATABASE_URL
        sync: false
      - key: MAILER_DSN
        sync: false
      - key: STRIPE_SECRET_KEY
        sync: false
      - key: STRIPE_DISABLE_SSL_VERIFY
        value: "0"
